server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs/access
      pattern: '%h %l %u [%{yyyy-MM-dd:HH:mm:ss}t] "%r" %s %b %D %{User-Agent}i' #'%h %l %u %t "%r" %s %b'
      max-days: 30
      encoding: utf-8
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: van-gateway
  config:
    import:
      - classpath:/domain/application.yml
      - classpath:/connector/application.yml
  devtools:
    livereload:
      enabled: false

springdoc:
  swagger-ui:
    path: /van-gateway/swagger-ui.html
    displayRequestDuration: true
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json

common:
  standard:
    cors:
      methods: GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD
      with-credential: true
      urls:
        - "http://swagger.subdomain.com:9001"
        - "http://localhost:9001"
        - "http://localhost:3000"
        - "http://172.27.1.11:3000"
        - "http://api-subdomain-01"
        - "http://api-subdomain-02"
        - "http://dev.van-gateway.com"
        - "http://dev01.van-gateway.com"
        - "http://dev02.van-gateway.com"
        - "http://dev03.van-gateway.com"
    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,metrics,loggers,status"
  health:
    db:
      enabled: false   # DB 헬스 체크 비활성화

pagehelper:
  helper-dialect: sqlserver2012