version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mysql:
    image: mysql:8.3
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # 루트용 비밀번호 변경
      MYSQL_USER: my-user # 기존 사용자 생성
      MYSQL_PASSWORD: my-password # 기존 사용자의 비밀번호
      MYSQL_DATABASE: mydb # 데이터베이스 초기 생성
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # 초기화 스크립트 위치 지정
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9099:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - kafka
volumes:
  mysql-data:
  zookeeper:
  kafka:
  kafdrop:
  postgres-data:
    driver: local
