spring:
  config:
    activate:
      - on-profile: local, dev

feign:
  cdp:
    url: http://localhost:9001
  sample:
    url: http://jsonplaceholder.typicode.com
  api-search:
    url: http://172.16.50.71:4002
    ksf-url: http://172.16.50.71:7614/ksf

endpoint:
  lottecard:
      eai: http://jsonplaceholder.typicode.com
      api: http://jsonplaceholder.typicode.com
  test:
    eai: http://jsonplaceholder.typicode.com
    api: http://jsonplaceholder.typicode.com
---
spring:
  config:
    activate:
      on-profile: stg, prd
feign:
  cdp:
    url: http://localhost:9003
  sample:
    url: http://jsonplaceholder.typicode.com
  api-search:
    url: http://172.16.50.71:4002
    ksf-url: http://172.16.50.71:7614/ksf

endpoint:
  lottecard:
    eai: http://jsonplaceholder.typicode.com
    api: http://jsonplaceholder.typicode.com
  test:
    eai: http://jsonplaceholder.typicode.com
    api: http://jsonplaceholder.typicode.com