spring:
  config:
    activate:
      - on-profile: local

endpoint:
  kicc:
    van: localhost
    van-port: 9010

---
spring:
  config:
    activate:
      - on-profile: dev

endpoint:
  kicc:
    van: 203.209.3.11
    van-port: 14110

---
spring:
  config:
    activate:
      - on-profile: stg

endpoint:
  kicc:
    van: 203.209.3.10
    van-port: 14110
---
spring:
  config:
    activate:
      on-profile: prd

endpoint:
  kicc:
    van: localhost
    van-port: 9010