spring:
  config:
    activate:
      - on-profile: local, dev

endpoint:
  sample:
    url: http://jsonplaceholder.typicode.com
  poc:
    van: localhost
    van-port: 9010
  search-engin:
    url: localhost:4002

---
spring:
  config:
    activate:
      on-profile: stg, prd

endpoint:
  sample:
    url: http://jsonplaceholder.typicode.com
  poc:
    van: localhost
    van-port: 9010
  search-engin:
    url: localhost:4002