plugins {
    id 'java'
    id 'jacoco'
}

configurations.configureEach {
    resolutionStrategy { cacheChangingModulesFor 0, 'seconds' }
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.jsoup:jsoup') {
            details.useVersion "3.0.4"
            details.because '오픈소스 취약점 blackduck workaround 조치'
        }
    }
}

dependencies {
    // module projects
    implementation project(":contract")
    implementation project(":connector")
    implementation project(":common-base")

    // jetbrains
    implementation "org.jetbrains:annotations:23.0.0"

    // sql logging
    implementation "org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1:1.16"

    // JsonNullable
    implementation group: 'org.openapitools', name: 'jackson-databind-nullable', version: '0.2.1'

    // Mybatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.2'
    implementation "org.mybatis:mybatis-typehandlers-jsr310:1.0.2"
    
    implementation 'org.apache.commons:commons-collections4:4.4'
    
    // Json Merge Patch Interface
    implementation 'jakarta.json:jakarta.json-api:2.1.1'

    // Json Merge Patch Library
    implementation "com.github.java-json-tools:json-patch:1.13"
    
    // cache
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation "net.sf.ehcache:ehcache:2.10.9.2"

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    // json-simple
    implementation "com.googlecode.json-simple:json-simple:1.1.1"

    // jsoup
    implementation "org.jsoup:jsoup:1.15.3"

    // commons-validator
    implementation "commons-validator:commons-validator:1.7"

    implementation 'org.apache.commons:commons-compress:1.26.0' // 강제 최신화

    // Apache POI
    implementation "org.apache.poi:poi:5.2.2"

    implementation 'org.apache.poi:poi-ooxml:5.4.0' //Office 2007
    implementation "org.apache.poi:poi-ooxml-full:5.2.2"
    implementation "org.apache.poi:poi-scratchpad:5.2.2"

    implementation "org.apache.poi:poi-ooxml-schemas:4.1.2"

    annotationProcessor "org.mapstruct:mapstruct-processor:1.5.3.Final"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:1.5.3.Final"

    // lombok-mapstruct-biding
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"

    // ConfigurationProperties
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testAnnotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    testCompileOnly "org.projectlombok:lombok:1.18.30"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.30"

    testImplementation 'org.jasypt:jasypt:1.9.3'

    implementation project(":common-base")

}

compileJava {
    options.compilerArgs += [
            '-Amapstruct.defaultComponentModel=spring',
            '-Amapstruct.defaultInjectionStrategy=constructor'
    ]
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

bootJar {
    enabled = false
}

jar {
    archiveClassifier = ''
    enabled = true
}

jacoco {
    toolVersion = "0.8.9"  // JaCoCo 버전 지정
}

jacocoTestReport {
    reports {
        xml.required = true
        csv.required = false
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }

    dependsOn test
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.0  // 최소 커버리지 비율 설정
            }
        }
    }
}
