jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    secret-key: Z29zMTAwNA==
    property:
      prefix: API(
      suffix: )

gram:
  type: lottecard
  file-path: resources/gram
  json-path:
    local: api-application/src/main/resources/gram/${gram.type}
    jar: classpath:gram/${gram.type}

db:
  active: true

spring:
  messages:
    basename: messages
    encoding: UTF-8
