jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    secret-key: Z29zMTAwNA==
    property:
      prefix: API(
      suffix: )

gram:
  file-path: resources/gram
  type: lottecard

file:
  json-path:
    dev: api-application/src/main/resources/gram/${gram.type}
    jar: classpath:gram/${gram.type}

db:
  active: false

spring:
  messages:
    basename: messages,errors,validation
    encoding: UTF-8
